119 improve api
maho3/ltu-ili pull request #123
Opened 2024-01-03 18:42 UTC by maho3

This PR implements numerous structural changes to the configurations of the Data/Inference/Validation stages, without much changes to how they work on the backend. The idea is to add various quality-of-life improvements that make it easier to understand the configurations and use them for testing 

Changes (so far):
- Removed the need to specify `backend` in the ValidationRunner. This is now gathered automatically from the imports.
- Removed the need to specify `n_walkers` in DelfiRunner (inference stage). It didn't make sense to specify `n_walkers` before the sampling stage, and it is redefined anyway in the EmceeSampler during validation.
- Removed the need to specify `n_data` and `n_params` in the DelfiRunner configuration. This info is now gathered automatically from the provided dataloader.
- Changed `output_path` -> `out_dir` and `posterior_path` -> `posterior_file` to match the naming conventions in loaders.py. Now, the ValidationRunner will only load the posterior from `out_dir / posterior_path` and subsequently save metrics in `out_dir`. I didn't see a reason why one would want to save metrics in a different directory from their posterior.
- Similar to the last change, `output_path` -> `out_dir` in the Inference stages.
- Added the ability to overload a loaded config file in each `from_config` function of the Data/Inference/Validation stages. This can be very useful if you want to iterate (in python) over many small changes to a configuration file. For example, one could change the training rate and the `out_dir` to save many models to different directories, each of which trained with a different training rate. Addresses #119 

Note a lot of files have changed, because we needed to propagate the naming changes to all the examples and tests. However, each commit is fairly simple and self-contained, so a reviewer can review the recent commits to see how the aforementioned changes were implemented.

Todo:
- [ ] Add an example of using the new flexible configurations for testing multiple architectures. This will use the `from_config` overloading feature.
- [ ] Allow NPE/NLE/NRE and SNPE/SNLE/SNRE to be loaded without specifying `sbi.inference` in the config.
- [ ] Update the jupyter tutorial with the new configuration structure.

2024-01-24 12:11 UTC, CompiledAtBirth commented
Currently running tests on a duplicate of this branch (seq_test to use a more recent torch than the setup.cfg).

2024-01-25 17:00 UTC, DeaglanBartlett requested changes
Really excellent work! Apart from a couple of minor comments I left, please can you add tests for the following, which are missing (according to Codecov):

- [x] - `utils.ndes_pt.load_nde_sbi()` should raise an error if the `model` is not one of `['mdn', 'maf', 'nsf', 'made']`
- [x] - An error is raised if neither `x` nor `x_obs` is provided for `PlotSinglePosterior`
- [ ] - The numpy seed is updated in `PlotSinglePosterior` if `x_obs` is `None` and a seed is provided
- [x] - Check samples can be saved from `PlotSinglePosterior`
- [ ] - Check `ValidationRunner.load_posterior_sbi()` works even if the posterior does not have a `name` attribute
- [x] - Check an error is raised if an invalid backend if provided to `InferenceRunner._parse_runner()`
- [x] - Check `DelfiRunner` still works even if you incorrectly use a device which isn't `cpu`
- [x] - Test loading of `engine_kwargs` for `DelfiRunner`
- [x] - Check for `ImportError` if the wrong engine is supplied to `SBIRunner._setup_engine()`
- [x] - Check for errors if one attempts to use `SBIRunnerSequential` with a loader which doesn't have attributes get_obs_data or simulate

2024-01-25 17:02 UTC, DeaglanBartlett commented
From @CompiledAtBirth on slack:

> For the SBISimulator loader specifically, the simulator function has to output a torch.Tensor of torch.Size((1,n)). The case is easy to handle once the user knows his simulator function must return that.

To avoid this mistake, please can you make sure it is well documented in the code and in the tutorial? We might as well do it in this PR as it is a minor thing to add

2024-01-28 22:32 UTC, maho3 commented on ili/validation/runner.py
> +            signatures = [""]*posterior_ensemble.num_components  # TODO: fix
This was meant to add signature functionality to the individual pydelfi models. However, this is a bit tricky as you need to redo the DelfiRunner save/load function again. Best saved for a future revision. I made a note of this in-line and removed the todo.

2024-01-28 22:33 UTC, maho3 commented on tests/test_sbi.py
> +    np.save('toy/theta.npy', theta)
Removed. This was likely a merge issue.

2024-01-28 22:36 UTC, maho3 commented
> From @CompiledAtBirth on slack:
> 
> > For the SBISimulator loader specifically, the simulator function has to output a torch.Tensor of torch.Size((1,n)). The case is easy to handle once the user knows his simulator function must return that.
> 
> To avoid this mistake, please can you make sure it is well documented in the code and in the tutorial? We might as well do it in this PR as it is a minor thing to add

Added comment in the code and tutorial.

2024-01-28 23:23 UTC, maho3 commented
> The numpy seed is updated in PlotSinglePosterior if x_obs is None and a seed is provided

This is rather difficult to test because we don't return what x_obs we choose, and the used np seed is difficult to access. I think this test isn't necessary, given the code is pretty clear as to what its doing.

2024-01-28 23:28 UTC, maho3 commented
> Check ValidationRunner.load_posterior_sbi() works even if the posterior does not have a name attribute

I just removed this functionality of `load_posterior_sbi`, because there should never be a case wherein an sbi posterior doesn't have a `name`. It is given `""` by default.

2024-01-29 09:17 UTC, DeaglanBartlett approved these changes

2024-01-29 09:18 UTC, merged