37 Setup dataloaders to sample new simulations
maho3/ltu-ili pull request #43
Opened 2023-02-27 14:13 UTC by DeaglanBartlett

Add dataloader which simulates instead of reads from file. Changes:

- New `SBISimulator` class in [loaders.py](https://github.com/maho3/ltu-ili/blob/main/ili/dataloaders/loaders.py) which can run simulations
- Added `num_rounds` and `x_obs` arguments to `__call__` function of [`SBIRunner`](https://github.com/maho3/ltu-ili/blob/main/ili/inference/runner_sbi.py#L22) to allow for multi-round inference
- Changed default weighting of ensemble to ensure that weights are always positive (problematic for active sampling if not)
- Observed `x` now given as argument to metrics so that sampling occurs with knowledge of this point
- Added new example to show how to use sbi's active sampler for toy example

2023-03-06 00:09 UTC, maho3 requested changes
Some small notes:
- I went ahead and pushed a removal of examples/ltu-ili-data since it was a symbolic link to a directory on infinity
- Should configs/val/sample.yaml and configs/val/multiround.yaml be merged since they're the same file?
- runner_sbi.py is getting hard to understand. Could you add quelque inline comments in __call__()?
- I left inline comments throughout Files Changed with minor fixes.

Bigger notes:
- Should x_obs and theta_obs be arguments that need be specified in the script example_*.py? I'm of the opinion that they shouldn't, as e.g. when you're doing inference on obs, you will want a loader to load them from file and not to have to build a loader -> loader.get_all_data -> submit them as parameters to runner and val_runner. Perhaps a more elegant solution is to have train and test loaders as arguments in runner and val_runner. What do you think?
- Before we close this, we should produce a comparison plot of posteriors trained with and without adaptive sampling, for a fixed number of simulations. The current toy example may be too simple to show much difference

2023-03-06 00:09 UTC, maho3 commented on ili/validation/runner.py
> +            theta_test, x_test = loader.simulate(prior)
If prior is None, raise Exception

2023-04-05 13:20 UTC, DeaglanBartlett commented on ili/inference/runner_sbi.py
> +            print('\nVAL LOSS:', val_loss, '\n')
No it's not. It will be removed in the next push

2023-04-26 15:51 UTC, maho3 commented on ili/inference/runner_sbi.py
> +                density_estimator = all_model[n].append_simulations(theta, x, proposal).train(
I checked and this does, by default, indeed always train the existing internal neural network every time we call train, without reinitialization ([link](https://github.com/mackelab/sbi/blob/5768a7c05aec799fe435167f75acaca483e5404d/sbi/inference/snpe/snpe_base.py#L304)). It also uses all training data that has been appended, so we only need pass the round-by-round theta's and x's. 

If you wanted a fresh neural network, you'd pass retrain_from_scratch=True. If you wanted to only use this round's data, you'd pass discard_prior_samples=True. Both of these are default = False.

Nothing to be done here, I just wanted to record this for future reference. :)

2023-04-26 15:56 UTC, maho3 commented on ili/dataloaders/loaders.py
> +        np.save(self.theta_path, theta.detach().cpu().numpy())
However, it should continue to only output the current round's data, as that is what `append_simulations` asks for.

2023-04-26 16:45 UTC, DeaglanBartlett commented on ili/inference/runner_sbi.py
I agree that is better. Will be added in next commit

2023-04-26 16:57 UTC, DeaglanBartlett commented on ili/inference/runner_sbi.py
> +                    device=self.device,
I'm not sure why I removed this before. I have re-added it in the latest commit

2023-04-27 18:05 UTC, maho3 approved these changes

2023-04-27 18:05 UTC, merged